# Generated by Django 6.0 on 2025-12-17 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(db_index=True, max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('link_factura', models.URLField(max_length=500)),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('queued', 'En cola'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('undelivered', 'No entregado')], default='queued', max_length=20)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('modo', models.CharField(default='REAL', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'db_table': 'mensajes_whatsapp',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
